### PR TITLE
Build: Compile with C++11 on Mac

### PR DESCRIPTION
**Pull request by kenashcraft**
When using Node 6.14.1 on Mac, I got compile errors:

```
> node-gyp rebuild

  CXX(target) Release/obj.target/sampling_heap_profiler/bindings/sampling-heap-profiler.o
../bindings/sampling-heap-profiler.cc:79:8: error: no member named 'unique_ptr' in namespace 'std'
  std::unique_ptr<v8::AllocationProfile> profile(
  ~~~~~^
../bindings/sampling-heap-profiler.cc:79:40: error: expected '(' for function-style cast or type construction
  std::unique_ptr<v8::AllocationProfile> profile(
                  ~~~~~~~~~~~~~~~~~~~~~^
../bindings/sampling-heap-profiler.cc:79:42: error: use of undeclared identifier 'profile'
  std::unique_ptr<v8::AllocationProfile> profile(
                                         ^
../bindings/sampling-heap-profiler.cc:81:35: error: use of undeclared identifier 'profile'
  AllocationProfile::Node* root = profile->GetRootNode();
                                  ^
4 errors generated.
```
This change forces C++11 along the lines of this [change](https://github.com/kuzzleio/boost-geospatial-index/commit/cbc018b4a0671e22ef9ffee104ddb7ab746bbcc8) as suggested by this [issue](https://github.com/kuzzleio/boost-geospatial-index/issues/1)

### CODE REVIEW

**Comment by ofrobots** [comment]
Hi @kenashcraft. Thanks for the PR. I am trying to understand the breaking build. I cannot reproduce it with my copy of `node-gyp` against node 6.14.1 on a Mac. It would be good for me to understand the scenario under which this breaks.

What version of `node-gyp` (I have 3.8.0) and what version of clang (I have clang-902.0.39.2) do you have on your system?

**Comment by kenashcraft** [comment]
Here is what I have and how I determined it.  I'm a bit of a newbie when it comes to node development, so it is possible that I have an old version of something getting picked up somehow.
```
~/code/sampling-heap-profiler[master]$ npm install

> fsevents@1.1.3 install /Users/kashcraft/code/sampling-heap-profiler/node_modules/fsevents
> node install

[fsevents] Success: "/Users/kashcraft/code/sampling-heap-profiler/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> heap-profile@0.3.1 install /Users/kashcraft/code/sampling-heap-profiler
> node-gyp rebuild

  CXX(target) Release/obj.target/sampling_heap_profiler/bindings/sampling-heap-profiler.o
../bindings/sampling-heap-profiler.cc:79:8: error: no member named 'unique_ptr' in namespace 'std'
  std::unique_ptr<v8::AllocationProfile> profile(
  ~~~~~^
../bindings/sampling-heap-profiler.cc:79:40: error: expected '(' for function-style cast or type construction
  std::unique_ptr<v8::AllocationProfile> profile(
                  ~~~~~~~~~~~~~~~~~~~~~^
../bindings/sampling-heap-profiler.cc:79:42: error: use of undeclared identifier 'profile'
  std::unique_ptr<v8::AllocationProfile> profile(
                                         ^
../bindings/sampling-heap-profiler.cc:81:35: error: use of undeclared identifier 'profile'
  AllocationProfile::Node* root = profile->GetRootNode();
                                  ^
4 errors generated.
make: *** [Release/obj.target/sampling_heap_profiler/bindings/sampling-heap-profiler.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kashcraft/.nvm/versions/node/v6.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/kashcraft/.nvm/versions/node/v6.14.1/bin/node" "/Users/kashcraft/.nvm/versions/node/v6.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kashcraft/code/sampling-heap-profiler
gyp ERR! node -v v6.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! heap-profile@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the heap-profile@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kashcraft/.npm/_logs/2018-09-19T16_11_16_740Z-debug.log
~/code/sampling-heap-profiler[master]$ "/Users/kashcraft/.nvm/versions/node/v6.14.1/bin/node" "/Users/kashcraft/.nvm/versions/node/v6.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" --version
v3.8.0
~/code/sampling-heap-profiler[master]$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
~/code/sampling-heap-profiler[master]$ clang++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Are you using nvm to install different node versions?

**Comment by ofrobots** [comment]
Thank! I updated XCode on my machine today, and I can reproduce this.

**Comment by ofrobots** [comment]
Thanks for the contribution. I have gone ahead and landed this.

**Comment by ofrobots** [comment]
heap-profile 0.3.2 published 🎉

**Pull request merged**
